frontend:
  port: 8080
  host: localhost

Peer2Peer:
  host: localhost
  Nodes:
    - location: "Kolkata"
      port: 8001
    - location: "Mumbai"
      port: 8002
    - location: "Delhi"
      port: 8003